#list omop concepts to check through for presence and location
omop_variables_to_check <- c("amount_unit_concept_id",
                             "amount_value",
                             "care_site_id",
                             "care_site_name",
                             "cause_concept_id",
                             "cause_source_value",
                             "cause_source_concept_id",
                             "condition_concept_id",
                             "condition_occurrence_id",
                             "condition_source_concept_id",
                             "condition_source_value",
                             "condition_start_date",
                             "condition_status_concept_id",
                             "condition_status_source_value",
                             "condition_type_concept_id",
                             "death_date",
                             "death_type_concept_id",
                             "denominator_unit_concept_id",
                             "drug_concept_id",
                             "drug_exposure_end_date",
                             "drug_exposure_id",
                             "drug_exposure_start_date",
                             "drug_source_concept_id",
                             "drug_source_value",
                             "drug_type_concept_id",
                             "episode_concept_id",
                             "episode_end_date",
                             "episode_id",
                             "episode_object_concept_id",
                             "episode_source_value",
                             "episode_start_date",
                             "episode_type_concept_id",
                             "gender_concept_id",
                             "gender_source_concept_id",
                             "gender_source_value",
                             "ingredient_concept_id",
                             "measurement_concept_id",
                             "measurement_date",
                             "measurement_id",
                             "measurement_source_concept_id",
                             "measurement_source_value",
                             "measurement_type_concept_id",
                             "month_of_birth",
                             "numerator_unit_concept_id",
                             "numerator_value",
                             "observation_concept_id",
                             "observation_date",
                             "observation_id",
                             "observation_period_end_date",
                             "observation_period_id",
                             "observation_period_start_date",
                             "observation_source_concept_id",
                             "observation_source_value",
                             "observation_type_concept_id",
                             "operator_concept_id",
                             "period_type_concept_id",
                             "person_id",
                             "person_source_value",
                             "place_of_service_concept_id",
                             "preceding_visit_occurrence_id",
                             "procedure_concept_id",
                             "procedure_date",
                             "procedure_end_date",
                             "procedure_occurrence_id",
                             "procedure_source_concept_id",
                             "procedure_source_value",
                             "procedure_type_concept_id",
                             "provider_id",
                             "provider_source_value",
                             "qualifier_source_value",
                             "specialty_source_value",
                             "unit_source_concept_id",
                             "unit_source_value",
                             "valid_end_date",
                             "valid_start_date",
                             "value_as_number",
                             "value_source_value",
                             "visit_concept_id",
                             "visit_detail_id",
                             "visit_end_date",
                             "visit_occurrence_id",
                             "visit_start_date",
                             "visit_type_concept_id",
                             "year_of_birth"
)






#omop_concept to medoc_concept
medoc_concepts <- list("amount_unit_concept_id" = "Treatment dose",
                    "amount_value" = "Treatment dose",
                    "care_site_id" = "generic",
                    "care_site_name" = "generic",
                    "cause_concept_id" = "generic*",
                    "cause_source_concept_id" = "generic*",
                    "cause_source_value" = "generic*",
                    "condition_concept_id" = c("Primary cancer diagnosis", "CCI", "Histological cell type"),
                    "condition_occurrence_id" = "generic",
                    "condition_source_concept_id" = "generic*",
                    "condition_source_value" = "generic*",
                    "condition_start_date" = "Date of primary diagnosis",
                    "condition_status_concept_id" = "Primary cancer diagnosis",
                    "condition_status_source_value" = "generic*",
                    "condition_type_concept_id" = "Primary cancer diagnosis",
                    "death_date" = "Date of death",
                    "death_type_concept_id" = "generic",
                    "denominator_unit_concept_id" = "generic",
                    "drug_concept_id" = c("Anti-cancer treatment name", "Molecular generic name"),
                    "drug_exposure_end_date" = "End date of drug treatment",
                    "drug_exposure_id" = "generic",
                    "drug_exposure_start_date" = "Start date of drug treatment",
                    "drug_source_concept_id" = "generic*",
                    "drug_source_value" = "generic*",
                    "drug_type_concept_id" = "generic",
                    "episode_concept_id" = "generic",
                    "episode_end_date" = "generic",
                    "episode_id" = "generic",
                    "episode_object_concept_id" = "generic",
                    "episode_source_value" = "generic",
                    "episode_start_date" = "generic",
                    "episode_type_concept_id" = "generic",
                    "gender_concept_id" = "Sex",
                    "gender_source_concept_id" = "Sex*",
                    "gender_source_value" = "Sex*",
                    "ingredient_concept_id" = "generic",
                    "measurement_concept_id" = c("Weight", "Height", "Performance status", "Disease stage", "Metastasis presence/absence", "Metastasis location", "Extent of debulking", "Biomarker name", "Biomarker measure", "Biomarker sample ID", "Radiotherapy dose"),
                    "measurement_date" = "generic",
                    "measurement_id" = "generic",
                    "measurement_source_concept_id" = "generic",
                    "measurement_source_value" = "generic",
                    "measurement_type_concept_id" = "generic",
                    "month_of_birth" = "Date of birth",
                    "numerator_unit_concept_id" = "generic",
                    "numerator_value" = "generic",
                    "observation_concept_id" = c("Menopausal status", "Participation in clinical trial"),
                    "observation_date" = "Date of trial consent",
                    "observation_id" = "generic",
                    "observation_period_end_date" = "generic",
                    "observation_period_id" = "generic",
                    "observation_period_start_date" = "generic",
                    "observation_source_concept_id" = "generic*",
                    "observation_source_value" = "generic*",
                    "observation_type_concept_id" = "generic",
                    "operator_concept_id" = "generic*",
                    "period_type_concept_id" = "generic",
                    "person_id" = "generic",
                    "person_source_value" = "Healthcare ID",
                    "place_of_service_concept_id" = "generic",
                    "preceding_visit_occurrence_id" = "generic*",
                    "procedure_concept_id" = c("Method of diagnosis", "Radiotherapy type", "Surgery type"),
                    "procedure_date" = c("Surgery date", "Radiotherapy start date"),
                    "procedure_end_date" = "Radiotherapy end date",
                    "procedure_occurrence_id" = "generic",
                    "procedure_source_concept_id" = "generic*",
                    "procedure_source_value" = "generic*",
                    "procedure_type_concept_id" = "generic",
                    "provider_id" = "generic",
                    "provider_source_value" = "generic",
                    "qualifier_source_value" = "generic*",
                    "specialty_source_value" = "generic",
                    "unit_source_concept_id" = "generic",
                    "unit_source_value" = "generic*",
                    "valid_end_date" = "generic",
                    "valid_start_date" = "generic",
                    "value_as_number" = c("Weight", "Height", "Performance status", "Disease stage", "Biomarker measure", "Extent of debulking"),
                    "value_source_value" = "generic*",
                    "visit_concept_id" = "Date of visits",
                    "visit_detail_id" = "generic",
                    "visit_end_date" = "Date of visits",
                    "visit_occurrence_id" = "Date of visits",
                    "visit_start_date" = "Date of visits",
                    "visit_type_concept_id" = "generic",
                    "year_of_birth" = "Date of birth")



