---
title: "`r params$centre` : Digione Onboarding Document"
author: "`r params$author`"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_float:
      collapsed: true
    number_sections: true
  word_document: default
params:
  centre: "Default Centre"
  author: "Default Author"
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(flextable)
library(dplyr)

is_word <- knitr::is_latex_output() == FALSE && knitr::pandoc_to() == "docx"


render_table <- function(df, caption, header = NULL) {
if (is_word) {

 max_col_width <- 1
 col_widths <- rep(max_col_width, ncol(df))

 ft <- flextable::flextable(df) %>%
 flextable::set_caption(caption) %>%
 flextable::set_table_properties(layout = "fixed", width = 0.9) %>%
 flextable::width(j = seq_along(col_widths), width = col_widths) %>%
 flextable::fontsize(size = 6, part = "all") %>%
 flextable::padding(padding = 3, part = "all") %>%
 flextable::align(align = "center", part = "all") %>%
 flextable::valign(valign = "top", part = "all")

 return(ft)

 } else {
 kbl <- kable(df, caption = caption) %>%
 kable_paper("hover", full_width = F) %>%
 kable_styling(position = "center")
 if (!is.null(header)) {
 kbl <- kbl %>% add_header_above(header)
 }
 return(kbl)
 }
}

```

# CDM Details

```{r cdm_details, echo = FALSE}


render_table(
 cdm_overall_snapshot,
 "Table 1.1 : CDM overview",
 c(" " = 1, "Summary of cdm details" = ncol(cdm_overall_snapshot) - 1)
)

```

# Summary of clinical tables 

```{r, echo = FALSE}

render_table(
 cdm_snapshot_clinical_condition,
 "Table 2.1 : Condition occurrence",
 c(" " = 1, "Summary of condition occurrence table" = ncol(cdm_snapshot_clinical_condition) - 1)
)
```

```{r, echo = FALSE}

render_table(
 cdm_snapshot_clinical_drug,
 "Table 2.2 : Drug exposure",
 c(" " = 1, "Summary of drug exposure table" = ncol(cdm_snapshot_clinical_drug) - 1)
)
```

```{r, echo = FALSE}

render_table(
 cdm_snapshot_clinical_meas,
 "Table 2.3 : Measurement table summary",
 c(" " = 1, "Summary of measurement table" = ncol(cdm_snapshot_clinical_meas) - 1)
)
```

# Summary of observation tables

```{r, echo = FALSE}
render_table(
 cdm_snapshot_obs,
 "Table 3.1 : Observation table summary",
 c(" " = 1, "Summary of observation table" = ncol(cdm_snapshot_obs) - 1)
)

```

# Vocabulary Mapping


```{r vocab_map, echo = FALSE}
render_table(
 mappingCompleteness,
 "Table 4.1 : Vocabulary mapping completedness",
 c(" " = 1, "Number and percentage of codes successfully mapped from source to OMOP convention, and number and percentage of records where vocabulary has been successfully mapped to OMOP convention" = ncol(mappingCompleteness) - 1)
)


```

# MEDOC to OMOP mapping

```{r, echo = FALSE}
render_table(
  medoc_concept_table,
  "Table 5.1 : MEDOC concept has valid concept id and locations",
  c(" " = 1, "Indicates the OMOP variable required for MEDOC concepts has a valid concept id, and their presence and location in the database (T/F)." = ncol(medoc_concept_table) - 1)
)

render_table(
  episode_table,
  "Table 5.2 : Episode table checks",
  c(" " = 1, "Are episode and event tables present and populated" = ncol(episode_table) - 1)
)

```
# Cancer phenotype

## Cancer diagnosis
```{r, echo = FALSE}
render_table(
  primary_snap_sliced,
  "Table 6.1 : Primary diagnosis -  concept ids",
  c(" " = 1, "Diagnosis by number of patients and domain (full list as csv in results folder)" = ncol(mets_snap_sliced_meas) - 1)
)

```

## Metastasis diagnosis
```{r, echo = FALSE}
render_table(
  mets_snap_sliced_meas,
  "Table 6.2 : Metastasis diagnosis - Measurement concept ids",
  c(" " = 1, "Metastasis diagnosis by number of patients and domain (full list as csv in results folder)" = ncol(mets_snap_sliced_meas) - 1)
)

```

```{r, echo = FALSE}
render_table(
  mets_snap_sliced_condition,
  "Table 6.3 : Metastasis diagnosis - Condition Occurrence concept ids",
  c(" " = 1, "Metastasis diagnosis by number of patients and domain (full list as csv in results folder)" = ncol(mets_snap_sliced_condition) - 1)
)

```

# Treatment checks

## Immunotherapy drugs

```{r drug_check_1, echo = FALSE}
render_table(
 summary_immuno_drugs,
 "Table 7.1 : Immunotherapy drug completedness",
 c(" " = 1, "Number of persons and records exposed to immunotherapy drugs, percentage of records with dose information, median drug exposure (days) per drug, proportion of records where drug exposure is not greater than one day (negative exposure days). Results are obscured where records are below 5 - 'results obscured' indicates whether this is the case" = ncol(summary_immuno_drugs) - 1)
)


```

## Chemotherapy drugs

```{r drug_check_2, echo = FALSE}

render_table(
  summary_chemo_drugs,
  "Table 7.2 : Chemotherapy drug completedness",
  c(" " = 1, "Number of persons and records exposed to chemotherapy drugs, percentage of records with dose information, median drug exposure (days) per drug, proportion of records where drug exposure is not greater than one day (negative exposure days). Results are obscured where records are below 5 - 'results obscured' indicates whether this is the case" = ncol(summary_chemo_drugs) - 1)
)
```

## Targeted therapy drugs

```{r drug_check_3, echo = FALSE}
render_table(
  summary_therapy_drugs,
  "Table 7.3 : Targeted therapy drug completedness",
  c(" " = 1, "Number of persons and records exposed to targeted therapy drugs, percentage of records with dose information, median drug exposure (days) per drug, proportion of records where drug exposure is not greater than one day (negative exposure days). Results are obscured where records are below 5 - 'results obscured' indicates whether this is the case" = ncol(summary_therapy_drugs) - 1)
)
```

## Radiotherapy treatment checks

```{r rt_check, echo = FALSE}
render_table(
  summary_radiotherapy,
  "Table 7.4 : Radiotherapy completedness",
  c(" " = 1, "Number of persons and records undergoing radiotherapy procedures, including counts and percentage of records where procedure end date occurs before procedure start date and number of procedures that occurred after the date of death" = ncol(summary_radiotherapy) - 1)
)

render_table(
  radiotherapy_dose_result,
  "Table 4.5 : Radiotherapy dosage",
  c(" " = 1, "Radiotherapy dosage availability" = ncol(radiotherapy_dose_result) - 1)
)

```

# Procedures check
```{r procedure_check, echo = FALSE}
render_table(
  summary_procedure,
  "Table 8.1 : All procedures check",
  c(" " = 1, "Number of cancer patients undergoing all procedures, including counts and percentage of records where procedure end date occurs before procedure start date and number of procedures that occurred after the date of death" = ncol(summary_procedure) - 1)
)


```
# TNM check

```{r, echo = FALSE}
render_table(
 tnm_result,
 "Table 9.1 : TNM code check",
 c(" " = 1, "Add TNM check info" = ncol(tnm_result) - 1)
)


```





